version: '3.8'

services:
  server:
    build: .
    ports:
      - "5555:5555"
    volumes:
      - ./src:/app/src 
      - ./.env:/app/.env
    command: python -m graph_server.server

  tests:
    build: .
    volumes:
      - ./src:/app/src
      - ./tests:/app/tests
      - ./.env:/app/.env
    environment:
      - PYTHONPATH=/app:/app/src
    command: python -m pytest tests/