version: '3.8'

services:
  server:
    build: .
    ports:
      - "5555:5555"
    volumes:
      - ./src:/app/src 

  tests:
    build: .
    volumes:
      - ./src:/app/src
      - ./tests:/app/tests
    command: python -m pytest tests/